name: 'Submodule - Build'

on:
  workflow_call:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout project sources'
        uses: actions/checkout@v5

      - name: 'Setup Node.js'
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Build'
        run: npm run build

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v5
        with:
          name: website
          path: dist/browser/
