name: Dependency check

on:
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    name: Dependency check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Dependencies
        run: |
          npm clean-install
