name: Lint check

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-check:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Lint check
        run: |
          npm run lint
